import RNFS from 'react-native-fs';
import Share from 'react-native-share';
import { PDFBOLT_API_KEY } from '@env';
import type { Strategy } from '../data/mockData';
import { fmtUSD, fmtPct } from '../data/mockData';
import { convertHtmlToPdf } from './pdfboltService';

// ── Helpers ─────────────────────────────────────────────

function isShareDismissed(error: any): boolean {
  return (
    error?.message?.includes('User did not share') ||
    error?.message?.includes('CANCELED') ||
    error?.code === 'ECANCELED'
  );
}

// ── Report HTML ─────────────────────────────────────────

function buildReportHtml(strategies: Strategy[], title: string): string {
  const totalInvested = strategies.reduce((s, st) => s + st.totalInvested, 0);
  const totalValue = strategies.reduce((s, st) => s + st.finalValue, 0);
  const avgRoi = strategies.length
    ? strategies.reduce((s, st) => s + st.roi, 0) / strategies.length
    : 0;
  const bestRoi = strategies.length ? Math.max(...strategies.map(s => s.roi)) : 0;
  const worstRoi = strategies.length ? Math.min(...strategies.map(s => s.roi)) : 0;

  const rowColor = (roi: number) => (roi >= 0 ? '#00E5A0' : '#FF4757');
  const rows = strategies
    .map(
      st => `<tr>
        <td class="asset">${st.asset}</td>
        <td>${fmtUSD(st.amount)} · ${st.frequency}</td>
        <td>${st.startDate} → ${st.endDate || '—'}</td>
        <td>${fmtUSD(st.totalInvested)}</td>
        <td style="color:${rowColor(st.roi)};font-weight:700">${fmtPct(st.roi)}</td>
        <td>${st.cagr ? fmtPct(st.cagr) : '—'}</td>
      </tr>`,
    )
    .join('\n');

  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${title}</title>
<style>
  *{margin:0;padding:0;box-sizing:border-box}
  body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;padding:16px;color:#111;max-width:800px;margin:0 auto}
  h1{color:#6C47FF;font-size:22px;margin-bottom:4px}
  .sub{color:#888;font-size:12px;margin-bottom:20px}
  .summary{background:#f5f3ff;padding:14px;border-radius:8px;margin-bottom:20px}
  .summary .row{display:flex;justify-content:space-between;padding:5px 0;font-size:13px;border-bottom:1px solid #e8e4ff}
  .summary .row:last-child{border-bottom:none}
  .summary .row span{color:#555} .summary .row b{color:#6C47FF}
  table{width:100%;border-collapse:collapse;font-size:12px;margin-bottom:20px}
  th{background:#6C47FF;color:#fff;padding:10px 8px;text-align:left;font-size:11px;text-transform:uppercase;letter-spacing:.5px}
  td{padding:10px 8px;border-bottom:1px solid #eee}
  .asset{font-weight:700}
  .footer{text-align:center;color:#999;font-size:10px;padding-top:20px;border-top:1px solid #eee}
</style></head><body>
  <h1>${title}</h1>
  <div class="sub">Generated by MicroDCA · ${new Date().toDateString()}</div>
  <div class="summary">
    <div class="row"><span>Strategies</span><b>${strategies.length}</b></div>
    <div class="row"><span>Total Invested</span><b>${fmtUSD(totalInvested)}</b></div>
    <div class="row"><span>Current Value</span><b>${fmtUSD(totalValue)}</b></div>
    <div class="row"><span>Avg ROI</span><b>${fmtPct(avgRoi)}</b></div>
    <div class="row"><span>Best ROI</span><b style="color:#00E5A0">${fmtPct(bestRoi)}</b></div>
    <div class="row"><span>Worst ROI</span><b style="color:#FF4757">${fmtPct(worstRoi)}</b></div>
  </div>
  <table><thead><tr><th>Asset</th><th>Amount · Freq</th><th>Period</th><th>Invested</th><th>ROI</th><th>CAGR</th></tr></thead><tbody>${rows}</tbody></table>
  <div class="footer">⚠️ Simulation only · Not financial advice · MicroDCA</div>
</body></html>`;
}

export async function exportReport(
  strategies: Strategy[],
  title = 'MicroDCA Portfolio Report',
): Promise<void> {
  const html = buildReportHtml(strategies, title);

  // Try PDFBolt first
  if (PDFBOLT_API_KEY && PDFBOLT_API_KEY.length > 10) {
    try {
      const pdfPath = await convertHtmlToPdf(html, PDFBOLT_API_KEY);
      try {
        await Share.open({
          url: `file://${pdfPath}`,
          type: 'application/pdf',
          title: 'Export Portfolio Report',
          filename: 'microdca_report',
        });
        return;
      } catch (e: any) {
        if (!isShareDismissed(e)) throw e;
        return;
      }
    } catch {
      // PDFBolt failed — silently fall back to HTML
    }
  }

  // Fallback: share as .html file
  const htmlPath = `${RNFS.CachesDirectoryPath}/microdca_report.html`;
  await RNFS.writeFile(htmlPath, html, 'utf8');

  try {
    await Share.open({
      url: `file://${htmlPath}`,
      type: 'text/html',
      title: 'Export Report',
      filename: 'microdca_report',
    });
  } catch (e: any) {
    if (!isShareDismissed(e)) throw e;
  }
}

// ── CSV ─────────────────────────────────────────────────

function buildCsv(strategies: Strategy[]): string {
  const header =
    'Asset,Amount,Frequency,StartDate,EndDate,TotalInvested,FinalValue,ROI,CAGR,MaxDrawdown,SharpeRatio\n';
  const rows = strategies
    .map((st) =>
      [
        st.asset,
        st.amount,
        st.frequency,
        st.startDate,
        st.endDate || '',
        st.totalInvested,
        st.finalValue,
        st.roi,
        st.cagr || '',
        st.maxDrawdown || '',
        st.sharpeRatio || '',
      ].join(','),
    )
    .join('\n');

  return header + rows;
}

export async function exportToCsv(strategies: Strategy[]): Promise<void> {
  const csv = buildCsv(strategies);
  const filePath = `${RNFS.CachesDirectoryPath}/microdca_export.csv`;

  await RNFS.writeFile(filePath, csv, 'utf8');

  try {
    await Share.open({
      url: `file://${filePath}`,
      type: 'text/csv',
      title: 'Export Portfolio',
      filename: 'microdca_export',
    });
  } catch (e: any) {
    if (!isShareDismissed(e)) throw e;
  }
}
